### ISSUE TITLE
Database export hosted on GitHub/Dropbox

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2-website#13]
Whenever a change is made to the database a cool down trigger of 24 hours will be launched. If no new changes are committed after that trigger an automated process will run to export the database into three formats, SQL, JSON and XML. These exported files will then be pushed to the Defacto2 GitHub repository, maybe as defacto2-databases?

The database data would be licensed as CC Attribution 4.0.

For the 'art & files' items a new entry containing a URL link that points to the file download should be included.

Also add a CSV (http://en.wikipedia.org/wiki/Comma-separated_values) export for easy use in legacy tools such as spreadsheets?

See GitHub limits.
https://help.github.com/articles/what-is-my-disk-quota

**Comment by bengarrett** [comment]
Done: https://github.com/Defacto2/database-exports
