### ISSUE TITLE
Server updated file packs

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2-website#8]
Create some shell scripts that will automatically incorporate any newly approved submitted files into their appropriate file pack. With each new file a file_id.diz should be updated with the latest additions. A file listing of the content could also be included.

These packs could also be applied to the magazine collections. So each magazine series could have a single file containing all the issues, in addition to the standard single issue downloads.

**Comment by bengarrett** [comment]
Redundant, instead implemented support for wget and DownloadThemAll.
